apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "globex-complaint-agent-build.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.job.copyGitlabToken.argocd.syncwave }}"
  name: copy-gitlab-token