apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: {{ include "globex-complaint-agent-build.name" . }}-trigger
  labels:
    {{- include "globex-complaint-agent-build.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.pipeline.argocd.syncwave }}"
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.git_http_url)
    - name: git-revision
      value: $(body.after)