{{- if eq .Values.image.registry "Quay" }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.pipeline.argocd.syncwave }}"
secrets:
  - name: registry-creds
imagePullSecrets:
  - name: registry-creds
{{- end }}
