apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: resync
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.pipeline.argocd.syncwave }}"
spec:
  steps:
    - args:
        - >-
          oc delete pod -n {{ .Values.resync.namespace }} -l
          app.kubernetes.io/instance={{ .Values.resync.label }}
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: resync
      computeResources: {}
