apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.resync.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.resync.argocd.syncwave }}"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops