apiVersion: v1
kind: Secret
metadata:
  name: {{ include "globex-complaint-agent.name" . }}
  labels:
    {{- include "globex-complaint-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "globex-complaint-agent.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    quarkus.oidc.auth-server-url={{ .Values.oidc.authServerUrl }}/realms/{{ .Values.oidc.realm }}
    quarkus.oidc.client-id={{ .Values.oidc.clientId }}
    quarkus.oidc.credentials.client-secret.value={{ .Values.oidc.clientSecret }}

    quarkus.langchain4j.openai.chat-model.model-name={{ .Values.llm.complaint.modelName }}
    quarkus.langchain4j.openai.api-key={{ .Values.llm.complaint.apiKey }}
    quarkus.langchain4j.openai.base-url={{ .Values.llm.complaint.baseUrl }}

    quarkus.langchain4j.openai.complaint.chat-model.model-name={{ .Values.llm.complaint.modelName }}
    quarkus.langchain4j.openai.complaint.api-key={{ .Values.llm.complaint.apiKey }}
    quarkus.langchain4j.openai.complaint.base-url={{ .Values.llm.complaint.baseUrl }}

    quarkus.http.cors.enabled={{ .Values.cors.enabled }}
    quarkus.http.cors.origins= {{ .Values.cors.origins }}
    quarkus.http.cors.methods={{ .Values.cors.methods }}
