{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "globex-complaint-agent.serviceAccountName" . }}
  labels:
    {{- include "globex-complaint-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "globex-complaint-agent.argocd-syncwave" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
