{{- if .Values.pipelines.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.pipelines.applicationName }}
  namespace: {{ .Values.pipelines.applicationNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.pipelines.argocd.syncwave }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: ""
    namespace: {{ .Values.pipelines.destinationNamespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
  source:
    repoURL: {{ .Values.pipelines.source.repoUrl }}
    targetRevision: {{ .Values.pipelines.source.targetRevision }}
    path: {{ .Values.pipelines.source.path }}
{{- end }}